# Generated by Django 4.2.2 on 2023-06-18 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
