# Generated by Django 4.2.2 on 2023-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_customusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
