# Generated by Django 4.2.2 on 2023-06-19 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('status_detalhe', models.CharField(max_length=30)),
                ('criado_em', models.CharField(max_length=30)),
                ('atualizado_em', models.CharField(max_length=30)),
                ('pago_em', models.CharField(blank=True, max_length=30, null=True)),
                ('descricao', models.CharField(max_length=30)),
                ('qr_code', models.CharField(max_length=1000)),
                ('qr_code64', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('api_version', models.CharField(max_length=30)),
                ('application_id', models.CharField(max_length=30)),
                ('date_created', models.CharField(max_length=30)),
                ('id_web', models.CharField(max_length=30)),
                ('live_mode', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hook.cobranca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
