# Generated by Django 4.2.2 on 2023-06-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='qr_code',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='qr_code64',
            field=models.CharField(max_length=6000),
        ),
    ]
