# Generated by Django 4.2.2 on 2023-06-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0002_alter_cobranca_qr_code_alter_cobranca_qr_code64'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
