# Generated by Django 4.2.2 on 2023-06-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0003_teste_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='mensagem',
            field=models.CharField(max_length=5000),
        ),
    ]
