# Generated by Django 4.2.2 on 2023-06-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0004_alter_teste_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='mensagem',
            field=models.CharField(max_length=100),
        ),
    ]
