# Generated by Django 4.2.2 on 2023-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0007_cobranca_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranca',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='pagamento_id',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='pago_em',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='qr_code64',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='status_detalhe',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='url',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='cobranca',
        ),
        migrations.AddField(
            model_name='cobranca',
            name='id_web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='mensagem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='atualizado_em',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='criado_em',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pagamento_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pago_em',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='qr_code',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='qr_code64',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status_detalhe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
