# Generated by Django 4.2.2 on 2023-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0008_remove_cobranca_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='teste',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
